### ISSUE TITLE
Research how to set up a server for hosting static assets

### ISSUE THREAD

**Issue by JohanObrink** [sebgroup/green#1]

**Comment by vsjolander** [comment]
@JohanObrink have you received any info from Niklas, Christopher or Martina? Is this issue still relevant?

**Comment by vsjolander** [comment]
Johan says that the conversation with Niklas, Christopher and Martin doesn't need to be followed up. This issue is more focused on where Greens static assest should be hosted.

**Comment by vsjolander** [comment]
One solution could be to use GCP services for static hosting of Green assets.
