### ISSUE TITLE
Button: Darkmode not good enough contrast

### ISSUE THREAD

**Issue by EldRoos** [sebgroup/green#1024]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### Component name

Button

### Description

Kristyna Mertova: 2023-07-10
Hello, we now updated the dark mode with buttons with Dark mode/Primary/Dark Blue 2 - Dark mode #2C9CD9. Against the dark background the color is more visible than light mode Light mode/Primary/Dark Blue #007AC7.  But the issue is the text. 

Our frontend dev are now getting accessibility errors.
Thoughts please?

[07-10 13:23] Andersson, Conny
Högnelid, Jonathan, could it be possible to use the lightmode DarkBlue2 for the darkmode-button instead? Or does anyone else have a good solution. 
 
 [07-10 13:49] Högnelid, Jonathan
Could be a quick fix, yes.

---
Change Dark mode/Primary/Dark Blue 2 - Dark mode #2C9CD9 to lightmode DarkBlue2.

### Current Behaviour

Contrast ratio: 3.05:1

### Expected Behaviour

Contrast ratio: more

**Comment by splashdust** [comment]
Button already uses #007AC7 in dark mode.
