### ISSUE TITLE
green-react tutorial/examples

### ISSUE THREAD

**Issue by kristsm** [sebgroup/green#1029]
### Description

Hi! Where can I find tutorials/examples on how to import and use green in react applications? https://sebgroup.github.io/green/latest/chlorophyll/?path=/story/introduction--page  have CSS explained, but there one cannot find any tutorial on how to use green with react (other than command for installing node module). Same goes for README.md in the green-react module where instructions stops at module import.

**Comment by splashdust** [comment]
You'll find the Storybook for React here: https://sebgroup.github.io/green/latest/react/

Hopefully that's enough to get you started!

Improving documentation will be an important focus area for Green going forward, so any feedback on things that are missing or hard to find or understand is most welcome! 👍
