### ISSUE TITLE
Issue with fonts when importing style

### ISSUE THREAD

**Issue by patriklarssson** [sebgroup/green#1054]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React, Chlorophyll

### Description

When importing a style in a tsx file like this
`import '@sebgroup/chlorophyll/scss/index.scss'`

The fonts cant be found
```
GET http://localhost:4200/fonts/SEBSansSerif-Regular.woff2 net::ERR_ABORTED 404 (Not Found)
:4200/fonts/SEBSansSerif-Regular.woff:1     GET http://localhost:4200/fonts/SEBSansSerif-Regular.woff 404 (Not Found)
:4200/fonts/SEBSansSerif-Bold.woff2:1     GET http://localhost:4200/fonts/SEBSansSerif-Bold.woff2 net::ERR_ABORTED 404 (Not Found)
:4200/fonts/SEBSansSerif-Medium.woff2:1     GET http://localhost:4200/fonts/SEBSansSerif-Medium.woff2 net::ERR_ABORTED 404 (Not Found)
:4200/fonts/SEBSansSerif-Bold.woff:1     GET http://localhost:4200/fonts/SEBSansSerif-Bold.woff net::ERR_ABORTED 404 (Not Found)
:4200/fonts/SEBSansSerif-Medium.woff:1     GET http://localhost:4200/fonts/SEBSansSerif-Medium.woff net::ERR_ABORTED 404 (Not Found)
```

### Steps To Reproduce

Create a react app
in main.tsx import green styling

```
import '@sebgroup/chlorophyll/scss/index.scss'
import { StrictMode } from 'react'
import * as ReactDOM from 'react-dom/client'
import App from './app/app'


const root = ReactDOM.createRoot(document.getElementById('root') as HTMLElement)
root.render(
  <StrictMode>
      <App />
  </StrictMode>
)
```

### Current Behaviour

Wrong import

### Expected Behaviour

Correct import

**Comment by vsjolander** [comment]
Hello and thanks for creating an issue!

You need to specify where the fonts are on your local machine. The default path is: `'../fonts'` and that's where its looking. So in your case you have two options: 

- Copy font files to `/fonts/SEBSansSerif-Regular.woff2`in the folder you are serving your app from. 
- Set up a `.scss` file where you import Chlorophyll with an altered `$font-path`. Change this to where you have the font files. See example below:

```scss
@use '@sebgroup/chlorophyll/scss' with (
  $font-path: './path/to/seb/font'
);
```

I see that this is (not clear in the documentation)[https://sebgroup.github.io/green/latest/react/?path=/docs/use--page] so i'll add it 👍

**Comment by vsjolander** [comment]
Closing this, if you need more help message me in teams!

**Comment by vsjolander** [comment]
Good point @splashdust! Since we have a dependancy on `@sebgroup/fonts` this makes sense!

Let's do this for a better experience and then MFE's will be told off when onboarded into shells I guess... :)

**Comment by patriklarssson** [comment]
That would be awesome since we are also in the mobile app (no shell) and would be good to not use any special solution for that :)
@vsjolander @splashdust
