### ISSUE TITLE
AlertRibbon success text is not white

### ISSUE THREAD

**Issue by patriklarssson** [sebgroup/green#1073]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

AlertRibbon

### Description

Text in AlertRibbon is black, --color variable is hsl( 0deg, 0%, 0% ) should be hsl( 0deg, 0%, 100% )

### Steps To Reproduce

```
<AlertRibbon
type="success"
header="header"
isCloseable={true}
>
text
</AlertRibbon>
```

### Current Behaviour

Text in AlertRibbon is black

### Expected Behaviour

Text in AlertRibbon is white

**Comment by splashdust** [comment]
@patriklarssson This should be fixed in recently released [1.15.4](https://github.com/sebgroup/green/releases/tag/%40sebgroup%2Fchlorophyll%401.15.4). Can you double check that you are on the latest version, and if you are still experiencing this issue, feel free to reopen this or comment here!
