### ISSUE TITLE
Dropdown: Add searchable support?

### ISSUE THREAD

**Issue by eweseong** [sebgroup/green#1083]
### Description

Looking at the documentation for react dropdown component, we notice that it provides the option to enable search feature via the `searchable` flag, but when we attempted to enable it, the component does not render the necessary inputs for a searchable dropdown. Is the flag not working as intended at this moment?

https://sebgroup.github.io/green/latest/react/?path=/docs/components-dropdown--dropdown#available-props

**Comment by splashdust** [comment]
@eweseong The Dropdown does support the `searchable` property in both Angular and React.

Here's how it looks when it is activated in the React component:
https://sebgroup.github.io/green/latest/react/?path=/story/components-dropdown--dropdown&args=searchable:true

**Comment by eweseong** [comment]
Thanks @splashdust, I was still using `green-react` v1, I will update to v2 to test out the new component
