### ISSUE TITLE
Unable to resolve fonts when using new angular esbuild

### ISSUE THREAD

**Issue by mattiasfloden** [sebgroup/green#1150]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Description

When using the new Angular esbuild which is default for new angular applications the builder fails to load the fonts:

![image](https://github.com/sebgroup/green/assets/54797257/34378c21-daf2-48af-a03d-4a7ca8f4de0e)

### Steps To Reproduce

1. Create a new angular project with Angular 17
2. Add SEB green and import styles as described in [Angular Green](https://sebgroup.github.io/green/latest/angular/?path=/story/get-started--page)
3.  Verify project is using new builder in angular.json:
```
...
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:application",
...
```
4. Build the application

### Current Behaviour

- If I replace variable (seb-font-path) in `@sebgroup > fonts > scss > _path.scss`  on all @font-face { ... } with a hard coded value "../fonts", then the build works.
- Using the "old" builder also works without any modifications.

**Comment by mackelito** [comment]
Any progress on this issue?

**Comment by mackelito** [comment]
as a temporary workaround you could try this:
```
@use '@sebgroup/chlorophyll/scss' with($font-path: '@sebgroup/fonts/fonts');
```

**Comment by splashdust** [comment]
> as a temporary workaround you could try this:
> 
> ```
> @use '@sebgroup/chlorophyll/scss' with($font-path: '@sebgroup/fonts/fonts');
> ```

☝️ This is the correct solution.

We might make this the default in a future major release, but for now it needs to be configured on the consumer side.

I'll add a note about this in the docs!
