### ISSUE TITLE
Dropdown: re-render selected label on options change (translations)

### ISSUE THREAD

**Issue by jsundqvist** [sebgroup/green#1192]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

green-angular 3.0.2, green-core 1.4.4

### Component name

dropdown

### Description

The datepicker should re-render the selected label when the options array is updated.
We are updating the options array with translations, so the keys/values are the same but the labels change.
![datepicker1](https://github.com/sebgroup/green/assets/19373567/da076e78-e41c-4490-b7f6-1cb9af088918)
![datepicker2](https://github.com/sebgroup/green/assets/19373567/3fd197db-4d83-43cf-bbe4-3ec1b1fcaaf6)

We currently run this little flip-flop to work around the issue, which would be nice to not have to do:

```
const previous = this.selected;
this.selected = previous == 'custom' ? 'today' : 'custom';
this.changeDetector.detectChanges();
this.selected = previous;
```

### Steps To Reproduce

1. Initialize the dropdown with a set of values and two-way binding
2. Replace the options array with a new one where the labels are different but the values/keys are the same.

### Current Behaviour

Selected label is not updated

### Expected Behaviour

Selected label is updated

**Comment by jsundqvist** [comment]
@splashdust should we reopen this one or do you want me to create a clone?

**Comment by splashdust** [comment]
Let's reopen!
