### ISSUE TITLE
Datepicker/dropdown: month/year dropdown lists appearing at wrong place when opened (Angular)

### ISSUE THREAD

**Issue by karolis-leonas** [sebgroup/green#1205]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported
- **I have checked the issues list, but this bug had not been reported anywhere else**

### For which framework/library you are reporting the bug

Angular

### Component name

Datepicker (maybe dropdown as well)

### Description

Hello all,

After updating our project's SEB Green to version 3.0.4 we've noticed a strange behaviour that for some reason our datepicker month and year selection lists are appearing not right below the dropdown button but somewhere else in the page. 

According to one of my colleagues @viliusmac it seemed to work properly on previous implementation of datepicker, but the issue must have started to appear after the fix https://github.com/sebgroup/green/pull/1181 and updating project's @sebgroup/green-angular version to 3.0.4. The issue does not seem to be reproduced at Angular datepicker's storybook page.

### Steps To Reproduce

We have noticed the issue at our project when running locally or running it as MFE within one of Business Arena's testing environments. 
Issue does not seem to reproduce at your storybook page here: https://sebgroup.github.io/green/latest/angular/?path=/docs/components-datepicker--custom-options .

Please contact me directly for more specifics about how do we manage to reproduce this issue.

### Current Behaviour

Datepicker's month and year dropdown list appears in a different, more random place:
![image](https://github.com/sebgroup/green/assets/37910061/1113ac2d-281a-42a5-9a35-36e87714b041)
![image](https://github.com/sebgroup/green/assets/37910061/331ecfed-4223-4bcc-bb27-7ea2ff3c649c)

### Expected Behaviour

Datepicker's month and year dropdown list should appear just below the dropdown button (standard dropdown behavior). Same as it does at https://sebgroup.github.io/green/latest/angular/?path=/docs/components-datepicker--custom-options

**Comment by splashdust** [comment]
@karolis-leonas I am hoping (fingers crossed) that this is fixed in https://github.com/sebgroup/green/releases/tag/%40sebgroup%2Fgreen-core%401.5.1

It is a sub-dependency of `@sebgroup/green-angular`, so just run `npm update` to get the latest patch release.

I will close this issue now, but we'll reopen if the problem remains in 1.5.1
