### ISSUE TITLE
Dropdown: border size/boldness is a bit different to one which was changed in datepicker

### ISSUE THREAD

**Issue by karolis-leonas** [sebgroup/green#1230]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

Dropdown (maybe datepicker)

### Description

Hello, this might seem a bit nitpicky, but after updating Green Angular to version [3.3.0](https://github.com/sebgroup/green/releases/tag/%40sebgroup%2Fgreen-angular%403.3.0) we have noticed that while datepicker's border color was changed, the dropdown still has a more darker, black border color for its dropdown button.

I think both of these should be aligned to have same border size for a more consistent user experience in our page (maybe others where both dropdown and datepicker are located) - maybe check with Design/UX people and decide/adjust both of them

### Steps To Reproduce

We have noticed the issue at our project when running locally or running it as MFE within one of Business Arena's testing environments.
Please contact me directly if you want to know the location of the project and where the issue itself is present within it.

### Current Behaviour

Dropdown and datepicker border color does not match.
![image](https://github.com/sebgroup/green/assets/37910061/1a3c4867-6e54-4a46-b691-4006b0d5dfb9)

### Expected Behaviour

Dropdown and datepicker border color should most likely match.

**Comment by splashdust** [comment]
@karolis-leonas It could be that you have an older version of Chlorophyll loaded on the page. If you have a direct dependency on Chlorophyll, I'd recommend removing it, as it is already a sub-dependency of the other packages. That way, there's less risk of it getting out-dated.

The default border color was updated a while back to the darker version you see in the Dropdown. For some reason this is hardcoded in the Dropdown (should probably be fixed), but the Datepicker use the global variable (`--sg-border-color`). So it seems like you are getting the old value of that variable here.

**Comment by karolis-leonas** [comment]
Adding chlorophyll manually to our project seemed to solve our issue :) For some reason just doing npm update did not help us, we needed to add Chlorophyll's newest version alongside Green Angular at our project's package.json and re-install dependenices to solve this issue. Thanks a lot @splashdust !
