### ISSUE TITLE
Dropdown: No Angular Darkmode

### ISSUE THREAD

**Issue by EldRoos** [sebgroup/green#1264]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### Component name

dropdown

### Description

Dropdown still is white on darkmode, which makes the focus be black on dark background.

### Expected Behaviour

Should switch do dark dropdown like chlorophyll and react.

**Comment by splashdust** [comment]
Closing this in favor of #1267, since this is not releated to the component itself.
