### ISSUE TITLE
Datepicker: No Angular Darkmode

### ISSUE THREAD

**Issue by EldRoos** [sebgroup/green#1265]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### Component name

datepicker

### Description

Datepicker still is white on darkmode, which makes the focus be black on dark background.

### Expected Behaviour

Should switch do dark Datepicker like chlorophyll and react.

**Comment by splashdust** [comment]
Closing this in favor of #1267, since this is not releated to the component itself.
