### ISSUE TITLE
Does not react to @media prefers-color-scheme

### ISSUE THREAD

**Issue by mackelito** [sebgroup/green#1268]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Chlorophyll

### Component name

all?

### Description

Components should use @media prefers-color-scheme

### Steps To Reproduce

[Open a page that uses chlorophyll and set darkmode for your browser.](https://sebgroup.github.io/green/latest/chlorophyll/iframe.html?viewMode=docs&id=components-form-elements-radio-button--radiobutton)

### Current Behaviour

No change

### Expected Behaviour

Expect component to use dark theme

**Comment by splashdust** [comment]
@mackelito You need to add the class `auto-mode` somewhere up-tree in the document. Here's an example: https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/use-cases-dark-mode-use-preferred-color-scheme--page

In a nut-shell:
* Add `auto-mode` to abide by `prefers-color-scheme`
* Add `dark-mode` to force dark mode
* Not setting either will default to light mode

That said, though, the current dark-mode implementation in Chlorophyll is spotty at best. We're working on a rewrite of the css variables/tokens setup that will eventually make it more consistent and easier to maintain.
