### ISSUE TITLE
Angular Dropdown in Dark mode has Black text except for highlighted option

### ISSUE THREAD

**Issue by rostigcykel** [sebgroup/green#1275]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

dropdown

### Description

![image](https://github.com/sebgroup/green/assets/5478080/0e219576-dbef-49a5-8428-c4de505a3106)

![image](https://github.com/sebgroup/green/assets/5478080/531fed4f-c1e1-4f5b-b2e0-7379451bb3b8)

Tried to overrule the browser rule that is applied but seemed to be beyond my knowledge to figure out a solution to this.

### Steps To Reproduce

1. Change Personalization -> Colors -> Choose your mode to Dark Mode in Windows
2. Open an application that has "auto-mode" set to support dark-mode theme as well as import the needed chlorophyll scss component to enable this.
3. Click dropdown to trigger the "drop" part
4. Any entry that is not highlighted is shown with barely visible Black text

### Current Behaviour

Black text is shown for dropdown-options in Dark-mode

### Expected Behaviour

White text is shown for dropdown-options in Dark-mode

**Comment by splashdust** [comment]
Hey @rostigcykel, thank you for opening an issue!
Could you double check that you are using the latest versions of all the packages, as a very similar issue was [recently fixed](https://github.com/sebgroup/green/pull/1246).

**Comment by rostigcykel** [comment]
This has already been fixed using the latest version and I had no issue fetching the latest version. Really sorry for not downloading the latest to check before opening issue. Closing this!

**Comment by splashdust** [comment]
@rostigcykel No problem at all! Thanks again for reporting issues 💚
