### ISSUE TITLE
Cannot build chlorophyll 3.3.0

### ISSUE THREAD

**Issue by Maximilian-R** [sebgroup/green#1293]
Following error at build:

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
1 │ @use '../../../../dist/libs/tokens/scss/pallet-2016' as pallet;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules\@sebgroup\chlorophyll\scss\tokens\_colors.scss 1:1                     @use
  node_modules\@sebgroup\chlorophyll\scss\components\use-green-scope\_index.scss 8:1  @use
  src\deferred.scss 2:1                                                               root stylesheet
  
 
Is this line intented to be in the src, cannot see any usage of it? @astrit 
https://github.com/sebgroup/green/blob/d23f58b0223bb3a615afa9439b35d2e7c6a57935/libs/chlorophyll/scss/tokens/_colors.scss#L1

**Comment by astrit** [comment]
Hi @Maximilian-R , yes it seems out of place will check and get back to you ✌️
