### ISSUE TITLE
Datepicker: Not rendering on Apple devices

### ISSUE THREAD

**Issue by kaylesaintjohn** [sebgroup/green#1368]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

Datepicker

### Description

Angular datepicker component is not rendering properly on Apple devices.
Tested using iPhone XR and iPad 2.
Unable to get error from console logs.

### Steps To Reproduce

1. Go to a page where datepicker is in an Angular project using Apple devices: iPad, iPhone
2. See blank page

### Current Behaviour

The Angular datepicker component (or the page itself) is not rendering at all.

### Expected Behaviour

Should be able to use the component across all devices and platforms

**Comment by splashdust** [comment]
Hey @kaylesaintjohn! We recently correct a few compatibility issues with older iOS versions, so it is possible that the problem you ran in to have been solved now. 

I tested it now on iPhone 7 with iOS 15.8.2, which is the oldest version we support, and It works on my machine™ at least :)

I'm closing this issue now, but if you still have issues in iOS 15.8.2 or higher, please re-open and we can investigate further!
