### ISSUE TITLE
Dynamic tooltip template based on chart and series type

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/green#248]
Currently with the default template, tooltips use a description list (dl tag) which probably works pretty okay for simple bar charts and lines with multiple series like in the example below: 
<img width="1092" alt="Screenshot 2021-10-28 at 16 53 51" src="https://user-images.githubusercontent.com/1632755/139281669-c8bfc9b0-e434-4386-8c0a-631f62934086.png">

For pie and donut charts however the first list item is empty eg. 

```html
<dl>
<dt></dt>
<dt>Name of serie and value</dt>
</dl>
```

Whereas we probably want something like this instead:
```html
<dl>
<dt>Name of serie</dt>
<dt>Value</dt>
</dl>
```

![image](https://user-images.githubusercontent.com/1632755/139281912-67d47b32-f1ad-41a9-9301-03fa82f98b33.png)

**Comment by vsjolander** [comment]
We need a clear usecase and design for this.
