### ISSUE TITLE
Separate UI text and Prose

### ISSUE THREAD

**Issue by syradar** [sebgroup/green#270]
When building web apps I often want different styles for UI and regular text. 
In the UI I want very few default styles so that I can position text more precisely and not have to worry about removing margins, etc.
But I also want beuatiful and easy to read text for larger text.

I have used the [prose-classes](https://github.com/tailwindlabs/tailwindcss-typography) from Tailwind which adds nice styling for all text inside the element it was applied to.
I suppose it could work the other way around as well adding a `ui` class for when you do not want any unwanted styling.

**Comment by vsjolander** [comment]
Hey @syradar 
In order to implement such a thing we need to specify this in SEBs design. Do you want to book a Green Coaching and we could talk about this further?

**Comment by syradar** [comment]
Sure, a meeting could be good.
