### ISSUE TITLE
Independent scss components

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/green#293]
It should be possible to import/use individual scss components from green i.e. they should not depend on each other and imorting a single file shouldn't break the build.

**Comment by hjalmers** [comment]
related to #448

**Comment by vsjolander** [comment]
Not as important since the goal is for all apps to use the same css file. If more work is needed on this create a new issue.

**Comment by mackelito** [comment]
Perhaps as that goal but still important.. when we are creating a feature with just a modal.. it does not make sense that this standalone component with no custom css gets over 400kb of css ;)
