### ISSUE TITLE
New component: Toolbar

### ISSUE THREAD

**Issue by ulde01** [sebgroup/green#345]
### Design decision
2021-11-18
![image](https://user-images.githubusercontent.com/45568194/149548807-f00779fb-30d3-4aaf-9e0c-2cb8f96fe80f.png)

### What is this
A toolbar is a series of buttons that enables the user to reach frequently, as well as less frequently, used actions or tools.

### Details
https://designlibrary.sebgroup.com/components/component-toolbar

### Component identifier
component-toolbar

Please close with a comment if issue is not relevant to you. 
Thank you! 
/Ulrika, Design library

Todos:
- [ ] Markup
- [ ] Tokens
- [ ] Story

**Comment by vsjolander** [comment]
Closing this since we are not adding new components to 2016. This will be build in some way in 2023.
