### ISSUE TITLE
Hide y-axis, x-axis and point on charts

### ISSUE THREAD

**Issue by ParhamGitijah** [sebgroup/green#348]
We need to be able hide y-axis, x-axis and point on charts. It seems that we cant do these stuff right now. (See attachment)

![Hide](https://user-images.githubusercontent.com/97948320/149915700-f7599a4e-4a87-41f7-b065-18240367b667.jpg)

**Comment by hjalmers** [comment]
So just the line and the tooltip should be visible I guess?

**Comment by ParhamGitijah** [comment]
Yes that is right. I see in our use case we have also x-axis visible but its good to have the option to hide x-axis too.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/97948320/150088345-0486ada4-c708-458e-b24c-6368157ea976.png">
