### ISSUE TITLE
Charts are not responsive to container

### ISSUE THREAD

**Issue by ParhamGitijah** [sebgroup/green#350]
We need to create small insight cards with a spline chart in it. The problem is that the chart will not fit into the card/container (see the attachment). 
Code:

`<div class="chart-container"><ngg-chart [settings]="settings"></ngg-chart></div>`

style:{
`.chart-container {
    position: relative;
    margin: 0;
    padding: 0;
    height: 100px;
    width: auto;
  }`
}

![Responsive](https://user-images.githubusercontent.com/97948320/149930515-50106d22-eb53-4e6e-8596-7709dba707ab.jpg)

**Comment by hjalmers** [comment]
I'll look into it, might be that we should use sparklines for this when chart are so small: https://naver.github.io/billboard.js/demo/#Plugins.Sparkline

Will it be possible to resize them or will they always be displayed in these small cards?

**Comment by ParhamGitijah** [comment]
They will always be in small cards in this use case. We need to implement charts like these in pic: 
I think it is a good Idea to have the possibility to resize charts. Right now they have always fix size (its a little big I think :) ).

<img width="868" alt="image" src="https://user-images.githubusercontent.com/97948320/150087677-6f1ef49e-e695-430a-9f5e-decedceb99ce.png">
