### ISSUE TITLE
React storybook cannot render react components

### ISSUE THREAD

**Issue by ethan-qsh** [sebgroup/green#354]
`TypeError: (0 , jsx_dev_runtime.jsxDEV) is not a function` is thrown when storybook is built on github but there is no issue when running it locally

@JohanObrink @hjalmers some other people have encountered this issue as well as per this issue https://github.com/nrwl/nx/issues/8403

**Comment by JohanObrink** [comment]
https://github.com/nrwl/nx/issues/8403
