### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by JohanObrink** [sebgroup/green#360]
A component for displaying tabular, filterable and sortable data is one of the most requested features for Green.

This is the current design:

https://designlibrary.sebgroup.com/components/component-table

Suggested design:

![image](https://user-images.githubusercontent.com/548783/150547316-655e1801-2e24-4e3a-ae12-7055884106a5.png)

- [ ]  Html markup

**Comment by syradar** [comment]
I found ReactTableLibrary on HackerNews today https://react-table-library.com/?path=/story/getting-started--demo
