### ISSUE TITLE
Angular install problem

### ISSUE THREAD

**Issue by SEBWilliamSundberg** [sebgroup/green#370]
I have installing green in my Angular app with: npm install @sebgroup/green-angular --save

package.json contains:
    "@sebgroup/chlorophyll": "^1.0.0-beta.3",
    "@sebgroup/green-angular": "^1.0.0-beta.3",

When I try to activate it in: app.module.ts
Adding: import { NggModule } from '@sebgroup/green-angular'

Then I get the following build problem:
Error: node_modules/@sebgroup/extract/lib/dropdown/types.d.ts:2:32 - error TS2307: Cannot find module 'react' or its corresponding type declarations.        

2 import { AriaAttributes } from 'react';

**Comment by hjalmers** [comment]
Which version are you using? I suspect it might be an issue with Beta.4 which was released a few days ago. 

It might sound a bit weird but if you're using Beta.4, try adding react as a dependency like this:

```
npm i react --save
````

And let me know if it solves the issue:)

**Comment by SEBWilliamSundberg** [comment]
After updating to latest Node & NPM and upgrading my project to Angular 13
the provided solution solved our problem.
