### ISSUE TITLE
Tab: New component - Tab navigation

### ISSUE THREAD

**Issue by ulde01** [sebgroup/green#373]
### Design decision
2022-01-27
![image](https://user-images.githubusercontent.com/45568194/151574315-ef709617-2ff7-4bc7-8d1a-979527c3e4d5.png)

### What is this
Tab navigation lets users to explore and switch between different content in our channels. The tabs are tied to the site navigation.

### Details
https://designlibrary.sebgroup.com/components/component-tabnavigation

### Component identifier
component-tabnavigation

### Follow up - development

Let me know if you have questions. And ss always, please comment and close if this issue is not relevant to you.
/Ulrika

Todos:
- [ ] Markup
- [ ] Tokens
- [ ] Story

**Comment by vsjolander** [comment]
These type of component should be "dumb" so the application handles things like routing.

**Comment by vsjolander** [comment]
This is more of a styling variant of tabs: https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-tabs--tabs
