### ISSUE TITLE
Stack layout

### ISSUE THREAD

**Issue by syradar** [sebgroup/green#418]
A layout/structure component that stacks children automatically for you, with gaps in between or distributed over the length of the parent and wrapping.

### Direction (default: horizontal)

Controls whether it stacks vertically or horizontally. Probably needs to be controllable per breakpoint.

### Spacing (default: 1rem)

Size of gaps between items, use Green Spacing

### Wrapping (default: true)

If the children should wrap around to the next row/column.

## Reference

- Shopify's Polaris Design System: https://polaris.shopify.com/components/structure/stack#navigation
- Implemented in my React App: https://github.com/syradar/yxans-klagan/blob/main/src/components/Stack.tsx

## Concept

![image](https://user-images.githubusercontent.com/10453338/154972570-ff968bfb-a5a8-4a3b-bdfe-0d080b9f7060.png)

## Todos
- [ ] Markup
- [ ] Tokens
- [ ] Story

**Comment by hjalmers** [comment]
Any benefits compared to these two that we're using today, or are you just looking for a component that wraps the behaviour?

https://getbootstrap.com/docs/5.1/layout/grid/
https://getbootstrap.com/docs/5.1/layout/css-grid/

**Comment by syradar** [comment]
Oh sorry, my email client swallowed the notifications.
I think a component that that just wraps the behaviour would be nice.
There is nothing wrong with classes like `flex flex-col gap-4` but it is a bit low level and it is easy to mess up and use different values.

```tsx
<Stack vertical>
  <div>vertical item</div>
  <div>vertical item</div>
  <Stack distribute>
    <Badge />
    <Badge />
    <Badge />
  </Stack>
</Stack>
```

![image](https://user-images.githubusercontent.com/10453338/160975170-a4dca4de-600d-4828-b81f-bd849560a7d5.png)

**Comment by vsjolander** [comment]
Hey @syradar 
Feels like this component closes this issue: https://sebgroup.github.io/green/latest/react/?path=/docs/components-layout-flexbox--flexbox

Or do you feel that it needs more functionality?

**Comment by syradar** [comment]
It just needs a `gap` property so that you can use it to space out things with consistent properties.
```ts
type SpacingWithBreakpoints = `${Breakpoint}-${GreenSpacing}`

interface FlexboxProps {
...
gap?: SpacingWithBreakpoints
}
```

**Comment by syradar** [comment]
Probably not needed anymore
