### ISSUE TITLE
Change "Dark Green 2" to #308800

### ISSUE THREAD

**Issue by ulde01** [sebgroup/green#433]
**Design decision 2022-03-08**

### Change
Dark Green 2 has been changed to #308800 (from #379D00).

### Reason
To improve contrast values, especially when we use it on components with white text on a green background. 

This is a general adjustment of the colour for all our frameworks. It will impact a number of components, such as Alert ribbon, Badge, Toast, Slide toggle and Tab navigation. I have informed Green, Vanilla and Bootstrap as I am hoping that I don't have to create issues for each component? Please let me know is that is the case!

Thanks!
/Ulrika

**Comment by ethan-qsh** [comment]
Hi, I will be closing this issue as Dark Green 2 is already set to `#308800` in rgb format `rgb(48, 136, 0)` 

![image](https://user-images.githubusercontent.com/62468447/159825240-c1628b4d-f7fd-4ffb-9f21-59997152935c.png)
