### ISSUE TITLE
Form components/directives

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/green#447]
**Some ideas:**

- [x] Dropdown
- [x] Datepicker
- [ ] Rangepicker
- [ ] Hint (for form info and error)
- [ ] Form group (which uses a slot for input, datepicker, dropdown etc).
- [ ] Checkbox group
- [ ] Radio button group
- [ ] Button group

Another approach code be: single or multi-select with different types 
eg. select single type dropdown
eg. select multiple type checkbox

```html
<ngg-select 
    type="dropdown" 
    options=[options]>
</ngg-select>

```
```html
<ngg-select 
    multiple="true"
    type="checkbox" 
    options=[options]>
</ngg-select>

```
as they would basically implement the same interface with `ControlValueAccessor`

**Comment by EldRoos** [comment]
@splashdust old issue, can we close?
