### ISSUE TITLE
Prevent background scroll for dropdown

### ISSUE THREAD

**Issue by hjalmers** [sebgroup/green#449]
Re-add body-scroll lock to prevent background scrolling for dropdown on mobiles.

**Comment by Maximilian-R** [comment]
Found some more issues while looking at this, will include a fix for them too:

- Limit listbox height so it cannot be larger than the screen
- Re-add Chevron/Arrow blue color
- Limit toggle text to one line
- Add close button background color css variable (only defined in alert component)

**Comment by Maximilian-R** [comment]
https://github.com/sebgroup/green/blob/34a2664128fe2d60e27aacdd4bbdf52fbdba2ed0/libs/chlorophyll/scss/components/close/_mixins.scss#L25

The close button in dropdown slide-up modal uses --sg-hsl-contrast which is not included in the light theme from @use '@sebgroup/chlorophyll/scss/components/use-green-scope'; 

I'm a bit lost in the color/theme setup, could you have a quick look? :) 

@hjalmers

**Comment by hjalmers** [comment]
@Maximilian-R yeah it's a bit messy at the moment:( I missed this comment yesterday but will take a look at it when I get a chance:)
