### ISSUE TITLE
💥 Dropdown updates

### ISSUE THREAD

**Issue by hemmahosjessi** [sebgroup/green#457]
## For input select
- [ ] Chevron Base 800
- [ ] Hover input border Base 500
- [ ] Selected input border Base 500 chevron pointing up

## For input select expanded section
- [ ]  Box shadow: 0 0 12px 0, 10% black (Maybe we can lab with this in code to get something we like?)
- [ ] Hover expanded value background Base 100
- [ ] Selected value font-weight medium, FA check icon aligned right
- [ ] Hover selected value background Base 100
- [ ] Search bottom border Base 200

Please let me know if I missed any specifications 🥰 and if you want me to write this in a different way. 
I have not specified any hover on the selected input select,  maybe that is something we could try out in code?

![dropdown_updates](https://user-images.githubusercontent.com/38652781/162976485-039c6c3d-fe8b-473c-b5d6-cf195fce3500.png)

**Comment by JessiNygrenWalhed** [comment]
Addition to Dropdown update:
We added a small variant, 32px.
Do you need anymore specs on that? 
![Uploading Screenshot 2022-06-02 at 13.44.10.png…]()
