### ISSUE TITLE
Checkbox update

### ISSUE THREAD

**Issue by hemmahosjessi** [sebgroup/green#458]
### Small but sweet adjustments to the Checkbox

- [ ] Border radius 2px
- [ ] Hover border Base 600
- [ ] Selected background Base 800
- [ ] Margin checkbox & label 12px

![checkbox_update](https://user-images.githubusercontent.com/38652781/162978174-52a7687b-dafd-43c4-9ef7-b892237da6f9.png)

**Comment by vsjolander** [comment]
This design has been implemented.
