### ISSUE TITLE
Dropdown: A11y evaluation

### ISSUE THREAD

**Issue by JohanObrink** [sebgroup/green#484]
Sit down with Ola Grönlund to evaluate the accessibility of the Dropdown components.

Turn all findings into issues and add them to the board.

**Comment by splashdust** [comment]
I've split this issue up into separate ones for Dropdown and Datepicker. Datepicker is now #1025

**Comment by splashdust** [comment]
@EldRoos Should we close this one and open a new issue when it's time to review the new 2023 version at some point in the future, or do you wanna keep this one open?

**Comment by splashdust** [comment]
Closing this one now. Let's open a new one when the 2023 design has been implemented.
