### ISSUE TITLE
RadioGroup: Default value

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#509]
Trying to set a default selected radio button in my radio group but can't seem to get it working.
```
<RadioGroup>
  <RadioButton label="Home" name="name" value="0" checked={state.selectedIndex === 0} />
</RadioGroup>
```

Works if I remove the RadioGroup and add some logic myself, is this the way to go?

**Comment by patrikfogelstrand** [comment]
Using the `defaultSelected` on `<RadioGroup>` works for me.

**Comment by vsjolander** [comment]
Fixed
