### ISSUE TITLE
btn-link

### ISSUE THREAD

**Issue by SEBEric** [sebgroup/green#534]
the bootstrap-class .btn-link is is destroyed by green. For example: It gives the element a border.
Please add btn-link to the not-section so its not overwritten by green

**Comment by SEBEric** [comment]
this is the code I'm using on my side to nullify the css from Green

.use-green .btn-link {
  border-width: 0 !important;
  &:hover,
  &:active,
  &.active {
    background-color: transparent !important;
    color: var(--intent-primary-background) !important;
  }
}

**Comment by splashdust** [comment]
I don't think its the responsibility of Chlorophyll to make sure that Bootstrap classes aren't affected within the `.use-green` scope.

Bootstrap and other 3rd part classes should remain unaffected outside of `.use-green`, but using Boostrap *inside* `.use-green` is unsupported.

Closing this issue now, but let me know if you have different opinions, and if so, let's discuss! @SEBEric @vsjolander
