### ISSUE TITLE
button small and large

### ISSUE THREAD

**Issue by SEBEric** [sebgroup/green#538]
Please add a small and large version of the buttons

this is the css I'm using to create a small version of the Green  button:

```
.use-green .btn-sm {
  padding: 0.28125rem 0.5rem !important;
  font-size: 0.875rem !important;
  line-height: 1.5 !important;
  border-radius: 4px !important;
}
```

**Comment by Maximilian-R** [comment]
You can apply the classes size-sm and size-lg to alter the size of buttons
