### ISSUE TITLE
Be able to modify "stepSize" and "count" options for axis in green-chart

### ISSUE THREAD

**Issue by ParhamGitijah** [sebgroup/green#556]
We found out that there is an issue with green-chart that we want to use. As you can see in pic below, to many ticks shows in y-axis for this diagram. That is why we think that a good solution to this problem is that we be able to set the y-axis stepsize of a chart in chartsettings. 

![image](https://user-images.githubusercontent.com/97948320/184089744-86f37e03-1953-4bc6-80a5-98bb255fe50b.png)

Todos:
### A suggestion of how solution looks like: 

There are two options in billboardjs which is very good to have: "stepSize" and "count". 
- The "count" option will automatically choose which values needs to show on y-axis but the number of ticks 
   will be equal with "count" value. 
- The "stepSize" sets axis tick step(interval) size. NOTE: stepSize will be ignored if axis.y.tick.count is 
  option is set.
  
  ### How do this in billboardjs: 
 ```
 axis: {
    y: {
      tick: {
     count: 5 //or stepSize:1000
      }
    }
  },
  
```

### How green-charts ChartSettings may look like:
```
export interface ChartStyle {
    fitHeightToParent?: boolean;
    axis?: {
        show: {
            x?: boolean;
            y?: boolean;
            y2?: boolean;
        } | boolean;
    };
    point?: {
        show?: boolean | 'focus';
    };
**ticks?:{
            y?: {
             count?: number
             stepSize?:number
            };
            y2?: {
             count?: number
             stepSize?:number
            };
}**
}
```

**Comment by splashdust** [comment]
Hello, I've added `ticksCount` and `stepSize` options to the `ChartStyle` interface in green-charts.

You can set it in the style options of the settings object, for example:
```typescript
style: {
  axis: {
    y: {
      label: 'Axis label',
      stepSize: 50,
      (or ticksCount: xxx)
    }
  }
}
```

Will this work for your use case?

For more details, check out #584

**Comment by ParhamGitijah** [comment]
Hi @splashdust! 

Sorry for late response. Thank you so much, yes this will work for us. When do you release this? I can not see these changes yet.  

BR
--Parham
