### ISSUE TITLE
Stepper is looping onchange event

### ISSUE THREAD

**Issue by danielgomez-seb** [sebgroup/green#559]
When using objects with usestate the onchange event is called every time, it's in a loop.

We would like the "name" property to be added and it would be great if we could get the the whole event returned instead of just the number.

BR Daniel & Atay

**Comment by vsjolander** [comment]
Created a PR for a solution!

Have yet to add the "name" prop and return the "whole event". Could you elaborate on this so we find the best solution:

- What do you need the "name" property for and how do you intend to use it?
- What do you mean when you say the whole event? :)

Thanks for contributing! 🪴

**Comment by splashdust** [comment]
I believe this issue was solved by #644
