### ISSUE TITLE
Dropdown list not showing on IBP

### ISSUE THREAD

**Issue by alrik-ahlstrom-seb** [sebgroup/green#560]
We're using scoped css (use-green) on our react MFE on IBP, and when you click the dropdown-button nothing happens.

I think it is because this element doesn't get created when the MFE is in IBP:
![image](https://user-images.githubusercontent.com/111437073/185137381-7b1689b1-492c-4818-8633-8c4914235796.png)

**Comment by vsjolander** [comment]
👋

I've now looked into the problem and it seems to be how the shell handles popovers.
More precise `IBP.Common.js` has this snippet in it:

```
$('body').on('touchend click', function (event) {
    if (!$(event.target).hasClass('m-help-popup') && !$(event.target).hasClass('popover-content')) {
        var popovers = document.getElementsByClassName('popover');
        if (popovers && popovers.length > 0) {
            $('.popover').remove();
        }
    }
});
```

work around would be to not use `popover` as a class. Would like to discuss more with the shell team on how we should think about this... But this is not a bug in Green.

**Comment by Maximilian-R** [comment]
In discussion with IBP

**Comment by antonseb** [comment]
Could you have another look at this issue? It works on desktop but on mobile the dropdown appears at the bottom of the screen and is hidden behind the browser menu.
