### ISSUE TITLE
Tooltip value (numbers) need to have white space for large numbers

### ISSUE THREAD

**Issue by ParhamGitijah** [sebgroup/green#575]
The problem is that the tool-tip value doesn't show very nice for larger numbers. We need green help to fix this. As pic below shows: 
**The value of tool-tip need to be in a prettier format like this with white spaces: 312 520. For larger number needs to be like 23 345 123 kr.**

![22](https://user-images.githubusercontent.com/97948320/189887935-170fbec1-77a3-47d3-9524-a58616e62be5.jpg)

### A suggestion of how solution looks like:
The template of tool-tip is like this today: 
```
const tmplTooltip = `
  <dl class="bb-tooltip-list">
    <dt>{=TITLE}</dt>
    {{
    <dd class="{=CLASS_TOOLTIP_NAME}" style="--color: {=COLOR}">
      <span>{=NAME} {=VALUE}</span>
    </dd>
    }}
  </dl>
`;
```

A func to fix this problem can be like this: 
```
numberWithSpaces(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
  }
```

Maybe Green can modify template and add this function instead? 

```
const tmplTooltip = `
  <dl class="bb-tooltip-list">
    <dt>{=TITLE}</dt>
    {{
    <dd class="{=CLASS_TOOLTIP_NAME}" style="--color: {=COLOR}">
      <span>{=NAME} {=numberWithSpaces(VALUE)}</span>
    </dd>
    }}
  </dl>

```

**Comment by splashdust** [comment]
Hello @ParhamGitijah, I have proposed a solution to this in #590.

Billboard can't parse function calls in its template syntax, but they do provide a way to intercept and apply formatting to values in tooltips. So I've added the formatting function you suggested above as the default format applied to numbers. I also added a way to supply your own function through the config if you need to override the default.

So in the style section you could add this for instance, to append `kr` to the number:
```typescript
style: {
  tooltipNumberFormat: value => `${value} st`
}
```

Note that the value parameter is the original unformatted number, so you would also need to add the spaces in this case.

**Comment by ParhamGitijah** [comment]
Hi @splashdust!

Sorry for late response. Thank you so much, yes this will work for us. When do you release this? I can not see these changes yet.

BR
--Parham
