### ISSUE TITLE
form field set descriptions disappearing when validated

### ISSUE THREAD

**Issue by mario-subo** [sebgroup/green#578]
https://github.com/sebgroup/green/blob/d32ebbbc9f25f1712dd607ae170a2f57a59e8ee6/libs/chlorophyll/scss/components/form/validation/_mixins.scss#L101

This rule causes this 
![image](https://user-images.githubusercontent.com/49055952/190373472-9129659a-92c8-4118-b91b-2a7f2903e79e.png)

to turn into this 
![image](https://user-images.githubusercontent.com/49055952/190373558-80088cb6-9425-46fa-b61f-41e3d13a76c7.png)
or 
![image](https://user-images.githubusercontent.com/49055952/190373604-2af84d46-7092-4cad-bcc0-b25974d05c84.png)

after it's been validated.

If there is no good reason for this maybe we should remove it?

**Comment by splashdust** [comment]
Agreed, it does not make sense that this is a hardcoded behaviour. If there is a use case for hiding the description in this manner, it's probably better to leave it up to application specific logic.

**Comment by vsjolander** [comment]
This styling is removed. Closing issue.
