### ISSUE TITLE
Dropdown (React): Using the arrow keys to change values doesn't trigger the onChange handler

### ISSUE THREAD

**Issue by daneriseb** [sebgroup/green#579]
When you use arrows keys to change the value in a Dropdown component, the onChange handler is not triggered.

This causes a bug in consume-loan-mfe (https://jira-general.sebank.se/browse/CON-2139).

@Maximilian-R Looks like you implemented arrow navigation. Do you know how to fix it?

This is how we use it:

````javascript
        <Dropdown
          options={state.newLoan.loanTerm.dropdown}
          onChange={handleLoanTerm}
          validator={toGreenErrorMessage(newLoan.loanTerm.error)}
          id="new_loan-loan-term-time-options"
        />

**Comment by Maximilian-R** [comment]
Do you mean that the dropdown should change value on arrow-navigation while the dropdown is closed but have focus?

**Comment by daneriseb** [comment]
I'm not sure what you mean, but it should be possible to use and change the chosen value in a dropdown using only the keyboard. Right now it looks like it works, since it's updated correctly on the screen, but the onChange handler is not called.

**Comment by Maximilian-R** [comment]
is it not triggered when hitting enter or leaving focus from the dropdown neither?
