### ISSUE TITLE
Readme "SEB Windows computer": HTTP_PROXY / HTTPS_PROXY might need to be unset

### ISSUE THREAD

**Issue by daneriseb** [sebgroup/green#580]
I was unable to install the node packages from home using the instructions in the Readme. I was able to fix it by removing the system variables HTTP_PROXY and HTTPS_PROXY on my Windows machine and logging off VPN.

**Comment by vsjolander** [comment]
I noticed that the git config and the npm config might cause problems when installing Green packages.

Thanks for pointing this out. Will add this to the documentation!

**Comment by patrikfogelstrand** [comment]
But... shouldn't the instructions actually be inside-seb-network and outside-seb-network?

## Inside
Connected to SEB Corporate or on VPN

### npm 
- config registry to point to artifactory
- proxy is not related here

### git
- proxy needed as you need to pass through the firewalls to connect to github.com
- only https is allowed through the proxy, so git can't be using ssh

## Outside
Connected to any public network, not on VPN

### npm
- config registry to npmjs
- proxy according to your network requirements (SEB proxy settings disabled of course)

### git
- proxy according to your network requirements
