### ISSUE TITLE
sugested change to the css of the alert

### ISSUE THREAD

**Issue by SEBEric** [sebgroup/green#589]
this is what I'm using to write over the alert css to be able to change the padding without it looking weird

div[role='alert'] {
  main {
    align-items: center;
    display: grid;
  }
  button.close {
    margin-top: 0 !important;
  }
}

**Comment by splashdust** [comment]
Hello @SEBEric, could you add some more context to this issue. What problem does this suggestion solve? Thank you.

**Comment by splashdust** [comment]
@SEBEric Thank you for the clarification!
