### ISSUE TITLE
last value in y2 and y axis will be hidden in Charts

### ISSUE THREAD

**Issue by ParhamGitijah** [sebgroup/green#608]
We have realized that the last value in y and y2 axis will not shows properly. I have mark this in pix below: 

![image](https://user-images.githubusercontent.com/97948320/194849574-5867015d-999d-4ec1-820c-7460fe79c56a.png)

![image](https://user-images.githubusercontent.com/97948320/194850075-b30dc2a8-b329-43d4-b82c-196dd1c891df.png)

Todos:
I have tried to solve this myself and overwrite green styling but I didn't succeed with that. Would you please look into that?

**Comment by splashdust** [comment]
Solved in #755
