### ISSUE TITLE
Mismatched color palette and forced button layout

### ISSUE THREAD

**Issue by Hybral** [sebgroup/green#621]
Hi,

I've noticed that the current color palette is not align with the current green design system. Many of the gray colors is off or have different names.

Another thing is that the button styling is forced on every button element with the exceptions of a small number of exceptions. We have numerous cases where we need a different design to the button than the base styling.

**Comment by splashdust** [comment]
Hey @Hybral, could you provide some examples of the cases where you need different styling for buttons? (Screenshots or links or markup.) It would be really helpful to have some examples of real-life use cases where the current implementation doesn't work well!

**Comment by splashdust** [comment]
Closing as lacking information. If this is still an issue for you and you have more information, leave a comment and we can reopen it! @Hybral
