### ISSUE TITLE
Issue with error messages for horizontal radiobuttons in IBP

### ISSUE THREAD

**Issue by antonseb** [sebgroup/green#633]
We use Green in our MFE on IBP and have an issue with error messages for horizontal radiobuttons. This error can only be reproduced on IBP. See below screenshot:
![image](https://user-images.githubusercontent.com/117288898/199510621-a920dde1-1d36-4ddc-83e2-c7489c01b4e1.png)

Link: https://apps.dev.sebank.se/cps/ibp/wow/3000/3500/wow3564.aspx?context=ibp

**Comment by daneriseb** [comment]
This can be closed, we will be fixed it in our repo.
