### ISSUE TITLE
Issue with dropdown options on IBP

### ISSUE THREAD

**Issue by antonseb** [sebgroup/green#634]
We use Green in our MFE on IBP and have an issue with dropdown options highlight. This error can only be reproduced on IBP. See below screenshot:
![image](https://user-images.githubusercontent.com/117288898/199511881-550b4568-aafa-4df0-bd26-301c98b51275.png)

Link: https://apps.dev.sebank.se/cps/ibp/wow/3000/3500/wow3564.aspx?context=ibp

**Comment by vsjolander** [comment]
This is due to IBP styling, not an issue with Green I'm afraid.

My suggestion would be to have a file where you can override these styling issues. When the app is migrated from IBP this file can be removed.

**Comment by daneriseb** [comment]
This can be closed, we will fix it in our repo.
