### ISSUE TITLE
Wrap Chlorophyll components for Angular

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#656]
Components are not presented in Angular Storybook which makes it seems that components are not developed. This was due to a decision that Angular should use the HTML to build your app so you can easier access the HTML.

But with a design system you shouldn't make alteration to your component so no need to access the HTML in Angular directly. Therefore we can wrap components to make the developer experience better.

**Comment by mackelito** [comment]
any progress on this?

**Comment by splashdust** [comment]
Closing this issue as obsolete.

Going forward, the underlying components will be native web components with encapsulated styles. Some of them will have Angular wrappers, mostly for backwards compatibility, but in general Angular has excellent support for using web components directly, with property binding and so on, so wrappers would be largely redundant.

"Green Core" will start rolling out during fall.

**Comment by mackelito** [comment]
@splashdust can we start using core now? (as a dev release or so?) :)
