### ISSUE TITLE
Cross framework testing

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#657]
Every component independent of framework (currently Angular & React) needs a comprehensive set of tests. Maybe, rather than writing cross framework components, we should focus on writing cross framework tests? Code reuse is still preferred over code duplication but with focus on shared tests, we wouldn't have to violate the coding principles of the frameworks to get anywhere.

Testing could be achieved in two steps:

1. State testing of a component given possible permutations. Basically every permutation documented in Chlorophyll can be tested to produce the same outerHTML.
2. Interaction testing of a component using basic selectors and interactions (focus, click, keypress etc) resulting in specific states.

The selectors for a specific components state and/or exposed value should also be shared to facilitate e2e testing in products using the components.

**Comment by vsjolander** [comment]
Not sure if this is relevant anymore due to migration to Green Core (Webcomponents). What would you say @splashdust?

**Comment by splashdust** [comment]
@vsjolander Yes, I agree! We should focus on having comprehensive tests of the Web Components in Core instead.

Ideally something along these lines:

Unit tests (web test runner with Playwright)
* API
* Interactions
* A11y

Visual regression testing
* ???

Integration tests
* Standalone application
  * Angular, React, framework-less
* Simulated shells

We have a pretty good setup for unit tests already, but the other areas are lacking.

But I think we can close this issue and open other more specific ones when we are ready to dig into this.
