### ISSUE TITLE
Dropdown close button 'X' in mobile view has wrong positioning

### ISSUE THREAD

**Issue by alalambda** [sebgroup/green#671]
Close button of the dropdown in the mobile view and on an iPhone (checked only in Safari) is incorrectly positioned in the container which makes a big space above the close button and whole dropdown and doesn't look good:

![image](https://user-images.githubusercontent.com/12610036/205053974-14c795f1-d5df-4ff7-9125-354d8d532030.png)

**Comment by vsjolander** [comment]
Should be fixed in: https://github.com/sebgroup/green/commit/85b0f5e639487a884c30eb58011869d5c05d3398
