### ISSUE TITLE
Terminal errors when using green in angular project

### ISSUE THREAD

**Issue by R0tenur** [sebgroup/green#697]
Green version: 1.0.0-beta.44
Angular version: 15.1.0

Used by:
```scss
@use '@sebgroup/chlorophyll/scss';
```

During build/serve following appears in terminal:
![bild](https://user-images.githubusercontent.com/12293736/211795425-3c704dc1-91ce-4d5c-a725-73638a67f94d.png)

**Comment by R0tenur** [comment]
> Just to be clear.. they are just warnings and will not really have an impact.. but they should not be apart of the code we import.

Fully aware, it's just annoying

**Comment by vsjolander** [comment]
This doesn't seem to be an issue with Green but rather with [ng cli](https://github.com/GoogleChromeLabs/critters/pull/129) or with [critters](https://github.com/angular/angular-cli/issues/22694).

A work around would be to configure your angular.json like this:

```json
"configurations": {
  "production": {
    "optimization": {
      "styles": {
        "inlineCritical": false
      }
    }
  }
}
```

But be aware if this affects performance like time to first paint.
