### ISSUE TITLE
Align checkboxes to the top when long lables

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#733]
<img width="376" alt="Screenshot 2023-02-14 at 16 27 04" src="https://user-images.githubusercontent.com/11420341/218782199-762eacaa-d9dd-4c04-8ffa-b8fb51ba04a4.png">

**Comment by astrit** [comment]
If you would `align-self: start;` the checkmark it self and perhaps add some margin on top for the visual parity, should fix it. 
Just playing around on this fork for future reference ✌️
