### ISSUE TITLE
Drop down does not open when clicking on the arrow

### ISSUE THREAD

**Issue by asafrank** [sebgroup/green#738]
Drop down lists doesn't fold-out when clicking on the arrow pointing down in the drop down fields. If you click anywhere else in the fields they fold out but not when you click on the arrow. 

 
![image](https://user-images.githubusercontent.com/125888439/220119337-20e3185f-735b-4456-8950-75b59bfec1d3.png)

Tested on: Desktop Edge
Team: ToConsume (Enkla lånet)

**Comment by EldRoos** [comment]
You are using react right?

Works here:
https://sebgroup.github.io/green/latest/react/?path=/docs/components-dropdown--dropdown

**Comment by asafrank** [comment]
Yes we are.

**Comment by vsjolander** [comment]
This was fixed in here: https://github.com/sebgroup/green/commit/3fb18bb24cf57b8accae4e41449ac58dc5d7e8e9

Not sure why it didn't close this issue when it was referenced in the PR 🤷 But that's why it works in the storybook. Upgrade to 1.0.2 and it should be fixed 😄
