### ISSUE TITLE
Translations in Green components

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#739]
Green components need some kind of translation library and functionality for common labels and aria-labels.

- This will make development easier since user of components doesn't need to think about standard phrases in for example the "Pagination"-component. (Go to first page, Go to last page, Go to next page)
- It will make sure that aria-labels are correct in most cases out of the box

The Angular way of handling translations doesn't seem like the best way to go since they merge translations into the app at build time.

React seems to have different i18n packages where the most popular is [i18next](https://react.i18next.com/).

## Current strategy

For now our strategy is to have English fallback translations with the option so send in overrides to the component that you handle translations for yourself. In the future we probably will add support for translations files and a standard way to implement translations in Green component.

**Comment by mackelito** [comment]
Why should a UI component library depend on translations at all?
Shouldn't they all be simple string inputs to the components?...

**Comment by splashdust** [comment]
The new Core library will use [@lit/localize](https://lit.dev/docs/localization/overview/) for translations.

To answer your question @mackelito, we want to have built-in translations for certain default texts. For example, the dropdown has some built-in copy when you select multiple options, "3 selected". We want this to work out of the box without consumers having to think about these built-in strings.

**Comment by splashdust** [comment]
Yes, it shouldn't be hard to support custom translations through `@lit/localize`.

By default, components will use English, and we will include optional Swedish translations initially, but other languages may need to be provided by the consumer. The localization features and translations will sit in a conditional export, so if you only need English, these features will add very little to your bundle size, as no other language strings will get imported.

Setting the correct language will need to be handled by the consumer for now. There will be a function called `setLocale` that you import and use to set the language, for example `setLocale('sv')`.

For more info, please check the link in my previous comment!
