### ISSUE TITLE
Datepicker: Not updated in form or on setValue

### ISSUE THREAD

**Issue by fazlizekiqi** [sebgroup/green#757]
We have a scenario where we need to use the datepicker in our search filters and have a reset button when the user wants to reset them. 

We tried to include the date picker inside of a form and do the form.reset() in order to reset the form to its initialed state but it is not working. 

We also tried to call specifically the formControl of the datePicker and tried to setValue(null) but this didnt work neither. 

A sample of our code...
```
// HTML file
<ngg-datepicker
                formControlName="startDate"
                [options]="startDateOptions"
                label="{{ 'startDate.label' | translate }}">
</ngg-datepicker>



TS FILE 
filterSearchFormGroup = new FormGroup({
  startDate: new FormControl(null),
  endDate: new FormControl(null),
});
 
// When clicking on reset button: 
clearSearchFilters(): void {
  this.filterSearchFormGroup.reset()
}
```

**Comment by splashdust** [comment]
I believe this was fixed in #964
