### ISSUE TITLE
Fieldset overflow bug

### ISSUE THREAD

**Issue by daneriseb** [sebgroup/green#759]
There seems to be a [bug ](https://stackoverflow.com/questions/8084343/google-chrome-fieldset-overflow-bug)in some browsers (at least in Chrome, Edge and Firefox) that makes the content of fieldset overflow. In our MFE we noticed it when using the RadioGroup, which creates a Fieldset. As a workaround we moved title/description to before the RadioGroup.

**Comment by vsjolander** [comment]
We've rebuilt the RadioGroup and it doesn't use fieldset anymore: https://sebgroup.github.io/green/latest/react/?path=/docs/components-radiogroup--default-story

Does the problem still exsist?
