### ISSUE TITLE
Dropdown: Rebuild

### ISSUE THREAD

**Issue by vsjolander** [sebgroup/green#779]
Dropdown component has issues with accessibility, design and performance. It is also built as a standalone "component application" (it's huge) in extract which makes it complicated for new developers/contributors to understand the component.

It should therefor be rebuild in both angular and React to make the component perform better and make it easier to maintain.

When rebuilding the component we should build a general component that handles popovers/modal/floating item placement connected to another UI element like a "List box" to a dropdown or a "Action menu" to a "More button". This component could be a Webcomponent wrapper and is used in both angular and React. But this would have to be investigated a bit more.

Perhaps the Dropdown listbox or other floating menus should be the dialog html element to more accessible?

Styling for List box items should be created in Chlorophyll and shared by using the same class name.

**Comment by vsjolander** [comment]
Related: #777

**Comment by splashdust** [comment]
Completed in #1016
