### ISSUE TITLE
Pagination component does not look as expected

### ISSUE THREAD

**Issue by R0tenur** [sebgroup/green#795]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Chlorophyll

### Component name

Pagination

### Description

Does not look good
https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-navigation-pagination--pagination
![bild](https://user-images.githubusercontent.com/12293736/226314360-855b94e7-5705-46a4-abd2-4c8ac8301c40.png)

**Comment by R0tenur** [comment]
@Maximilian-R

**Comment by Maximilian-R** [comment]
fixed #796
