### ISSUE TITLE
Enable font-smooth on the entire library

### ISSUE THREAD

**Issue by astrit** [sebgroup/green#798]
### Font Smooth
When implementing `font-smooth`, we should be careful to consider MacOS and Windows support 

Source:
[font-smooth](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth)

`antialiased` — Smooth the font on the level of the pixel, as opposed to the subpixel. Switching from subpixel rendering to anti-aliasing for light text on dark backgrounds makes it look lighter.

-----------

### Text Rendering
Also `text-rendering` we should take in consideration either `optimizeLegibility` or `optimizeSpeed`
 
Source:
[text-rendering](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering)

`optimizeSpeed` — The browser emphasizes rendering speed over legibility and geometric precision when drawing text. It disables kerning and ligatures.

`optimizeLegibility` — The browser emphasizes legibility over rendering speed and geometric precision. This enables kerning and optional ligatures.

-----------

### Example

```css 

-webkit-font-smoothing: antialiased;
-webkit-text-size-adjust: 100%;
text-rendering: optimizeLegibility;
  
 ```

**Comment by splashdust** [comment]
I think the current default in Chlorophyll already looks OK:

```css
text-rendering: optimizeLegibility;
...
-moz-osx-font-smoothing: grayscale;
-webkit-font-smoothing: antialiased;
```

Closing this one now, but feel free to re-open if you think we should change this setup @astrit
