### ISSUE TITLE
🚀 Roadmap

### ISSUE THREAD

**Issue by astrit** [sebgroup/green#818]
## Libraries

|      | Library                        | Version |                                                                     |
| :--: | :----------------------------- | :-----: | ------------------------------------------------------------------: |
| [^1] | @sebgroup/green-angular-charts | `1.1.0` | [Storybook](https://sebgroup.github.io/green/latest/angular-charts) |
| [^2] | @sebgroup/green-angular        | `1.2.0` |        [Storybook](https://sebgroup.github.io/green/latest/angular) |
| [^3] | @sebgroup/green-charts         | `1.1.0` |         [Storybook](https://sebgroup.github.io/green/latest/charts) |
| [^4] | @sebgroup/chlorophyll          | `1.5.0` |    [Storybook](https://sebgroup.github.io/green/latest/chlorophyll) |
| [^5] | @sebgroup/extract              | `1.2.1` |                                                                     |
| [^6] | @sebgroup/green-react-charts   | `1.0.1` |   [Storybook](https://sebgroup.github.io/green/latest/react-charts) |
| [^7] | @sebgroup/green-react          | `1.3.0` |          [Storybook](https://sebgroup.github.io/green/latest/react) |

---

## Components

|     | Component       | Chlorophyll | React | Angular |
| :-: | :-------------- | :---------: | ----: | ------: |
| 01  | accordion       |     ✅      |    ✅ |      ✅ |
| 02  | alert-ribbon    |     ✅      |    ✅ |      ❌ |
| 03  | backdrop        |     ✅      |    ❌ |      ❌ |
| 04  | badge           |     ✅      |    ✅ |      ✅ |
| 05  | border          |     ✅      |    ❌ |      ❌ |
| 06  | brand           |     ✅      |    ❌ |      ❌ |
| 07  | button          |     ✅      |    ❌ |      ✅ |
| 08  | card            |     ✅      |    ✅ |      ❌ |
| 09  | close           |     ✅      |    ❌ |      ❌ |
| 10  | container       |     ✅      |    ❌ |      ❌ |
| 11  | datepicker      |     ✅      |    ✅ |      ✅ |
| 12  | dropdown        |     ✅      |    ✅ |      ✅ |
| 13  | fonts           |     ✅      |    ❌ |      ❌ |
| 14  | form            |     ✅      |    ✅ |      ❌ |
| 15  | grid            |     ✅      |    ❌ |      ❌ |
| 16  | icon            |     ✅      |    ✅ |      ❌ |
| 17  | link            |     ✅      |    ✅ |      ❌ |
| 18  | list            |     ✅      |    ✅ |      ❌ |
| 19  | modal           |     ✅      |    ✅ |      ✅ |
| 20  | navbar          |     ✅      |    ✅ |      ❌ |
| 21  | pagination      |     ✅      |    ❌ |
| 22  | popover         |     ✅      |    ❌ |      ❌ |
| 23  | progress-circle |     ✅      |    ❌ |      ❌ |
| 24  | reset           |     ✅      |    ❌ |      ❌ |
| 25  | select          |     ✅      |    ✅ |      ❌ |
| 26  | skeleton-loader |     ✅      |    ❌ |      ❌ |
| 27  | slide-toggle    |     ✅      |    ❌ |      ❌ |
| 28  | slider          |     ✅      |    ✅ |      ✅ |
| 29  | table           |     ✅      |    ❌ |      ❌ |
| 30  | tabs-bar        |     ✅      |    ❌ |      ❌ |

[^1]: **@sebgroup/green-angular-charts (1.1.0)** — A charting library for Angular applications, providing a set of customizable and responsive chart components based on the Green design system.
[^2]: **@sebgroup/green-angular (1.2.0)** — A UI component library for Angular applications, following the Green design system. It includes a collection of reusable components such as buttons, forms, and navigation elements.
[^3]: **@sebgroup/green-charts (1.1.0)** — A standalone charting library based on the Green design system, suitable for use in any JavaScript project. It provides a collection of responsive and customizable chart components.
[^4]: **@sebgroup/chlorophyll (1.5.0)** — A CSS framework for building web applications based on the Green design system. It includes a set of pre-built styles, layout utilities, and design tokens for creating consistent user interfaces.
[^5]: **@sebgroup/extract (1.2.1)** — Extract is where all the business logic of Green components lives so that it can be shared between Angular and React implementations. It is called Extract since the normal way of creating a component is within Angular and React and then extracting the common logic.
[^6]: **@sebgroup/green-react-charts (1.0.1)** — A charting library for React applications, providing a set of responsive and customizable chart components based on the Green design system.
[^7]: **@sebgroup/green-react (1.3.0)** — A UI component library for React applications, following the Green design system. It includes a collection of reusable components such as buttons, forms, and navigation elements.

**Comment by splashdust** [comment]
Closing this one for now, since the information has become outdated. I still like the concept, but I feel like it has to be automated to be useful in the long run!

In the mean time, for anyone looking for component statuses, check here: https://designlibrary.sebgroup.com/components-matrix
