### ISSUE TITLE
Unwanted margin for ButtonGroups inside of forms

### ISSUE THREAD

**Issue by syradar** [sebgroup/green#825]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React, Chlorophyll

### Component name

ButtonGroup, Group, FormGroup

### Description

- There is no margin between Label and ButtonGroup. 
- There is `0.5rem` unwanted margin below the ButtonGroup since it is inside the a group. 
- The `id` property is not allowed on a `<ButtonGroup />`.

![image](https://user-images.githubusercontent.com/10453338/229313823-f29a1973-4a8c-4f43-b1b9-90034a3c1036.png)

![image](https://user-images.githubusercontent.com/10453338/229313843-15a43541-220d-47f5-8427-61065f095722.png)

### Steps To Reproduce

1. Use TypeScript and React.
2. Add a ButtonGroup as an input inside of a FormGroup.

### Current Behaviour

- `id` is not allowed on the ButtonGroup
- The margins/spacing is flipped.

### Expected Behaviour

`id` should be allowed on the ButtonGroup Component.

The margin should be between the Label and the Input (in this case a ButtonGroup)

Less magic for components, or clearer rules. By using the group I also got all of these CSS rules that I did not expect

![image](https://user-images.githubusercontent.com/10453338/229314020-b1c5821b-a5c3-4e15-942e-f936a8196d5a.png)

Is there any plans of a more utility based CSS framework or would you be open for a SEB Green Config for something like Tailwind?

**Comment by astrit** [comment]
Is this the setup you are looking for ? 

<img width="1077" alt="CleanShot 2023-04-03 at 15 31 21@2x" src="https://user-images.githubusercontent.com/2398447/229524870-8aab6687-b1f4-49a4-9103-a6c802c7a03a.png">

Example: 
<img width="526" alt="CleanShot 2023-04-03 at 15 33 42@2x" src="https://user-images.githubusercontent.com/2398447/229525376-1db878c6-3dab-435a-8c50-469929629d38.png">

**Comment by syradar** [comment]
Yeah I guess. Right now I solved by adding flex-column to the label and buttongroup's parent and gap of 8px (Spacing3 right)

**Comment by astrit** [comment]
> Yeah I guess. Right now I solved by adding flex-column to the label and buttongroup's parent and gap of 8px (Spacing3 right)

Yes with flex and gap things would be better but for now I pushed a little fix.

**Comment by splashdust** [comment]
To add to @astrit's reponse, the `ButtonGroup` is actually the [Segmented Control](https://designlibrary.sebgroup.com/components/component-segmented-control) component from Design LIbrary, which is not meant to be used as a form input.

This is currently unclear in Green though, especially with the unaptly named `ButtonGroup` component, and I think we need to improve documentation and provide better examples to explain what the components were designed for.
