### ISSUE TITLE
Datepicker: Label cannot be changed

### ISSUE THREAD

**Issue by siva87** [sebgroup/green#881]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

Datepicker

### Description

The label for datepicker is having hardcoded string value as "Date".

It instead should represent the date in the user interface. eg. "Claim Date", "Submission Date", "Application Date", etc

### Steps To Reproduce

1. Add a datepicker component to the page
2. Hardcoded label is rendered together with Datepicker (no option to change or remove label value)

### Current Behaviour

Datepicker label is having hardcoded string value as "Date"

### Expected Behaviour

Ability to change datepicker label via props

**Comment by GomathiDevarajan** [comment]
I am also having this issue
