### ISSUE TITLE
Datepicker: Disabled Dates are not grayed out

### ISSUE THREAD

**Issue by wunsamting** [sebgroup/green#885]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

Datepicker

### Description

![image](https://github.com/sebgroup/green/assets/133340015/db8a1a0d-1dfa-472a-9e67-5315f8e8b768)
Passed the maxDate props to the datepicker, expected the dates beyond maxDate is grayed out, but it is not, only dates in the following month are grayed out. 

### Steps To Reproduce

1. Add a datepicker component to any page
2. Set the maxDate to today's date, for example (12th May 2023)
3. Future dates like 13th May and beyond should be grayed out

### Current Behaviour

Dates beyond maxDate is not grayed out

### Expected Behaviour

Dates beyond maxDate is grayed out

**Comment by GomathiDevarajan** [comment]
I am also having this issue
