### ISSUE TITLE
AlertRibbon: Warning for using CMS markup type in content

### ISSUE THREAD

**Issue by aurimasvarnelis** [sebgroup/green#895]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

AlertRibbon

### Description

https://github.com/sebgroup/green/blob/main/libs/react/src/lib/alert-ribbon/alert-ribbon.tsx

Having difficulties when using CMS markup translation fields in the `AlertRibbon` component, because `alert-ribbon__content` has `<p>` for children elements. The markup field from CMS can have either `<p>` or `<div>` elements and thus throwing this similar warning for both of them: 
![image](https://github.com/sebgroup/green/assets/27087826/88604aea-f041-48e8-af8a-c0ba19ca2b25)

This happens because paragraph should not nest `<p>` or `<div>` elements.

**Comment by splashdust** [comment]
I would argue that the warning is actually correct in this case, and that the use of divs or paragraphs or other markup, except perhaps simple formatting like `<strong>` and `<em>`, is not supported in AlertRibbons.

Basically, there should never be more than a single paragraph in an AlertRibbon, so if the content is editable in a CMS you should use a limited content field. Something that is limited to around 75 characters and perhaps only accepts plain text. It's inadvisable to use WYSIWYG content in an AlertRibbon.

If the CMS does not support this, you should sanitize the content before handing it off to the AlertRibbon.
