### ISSUE TITLE
Slider: Input field is too high

### ISSUE THREAD

**Issue by daneriseb** [sebgroup/green#902]
### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

React

### Component name

Slider

### Description

According to "SEB Design System" in Figma the slider input field should have a height of 32px. Now it is 48px.

**Comment by EldRoos** [comment]
I confirm Figma and Green have different sizes (though it is 44px not 48px.

Will check if at least the mobile version should have normal bigger sized input field.
