### ISSUE TITLE
Modal: Jest test problems

### ISSUE THREAD

**Issue by mackelito** [sebgroup/green#952]
Problem with jest tests when using components from NggModalModule

### Bug already reported ?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Angular

### Component name

Modal

### Description

Test suite failed to run
       
           Jest encountered an unexpected token
       
           Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.
       
           Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.
       
           By default "node_modules" folder is ignored by transformers.
       
           Here's what you can do:
            • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
            • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
            • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
            • If you need a custom transformation specify a "transform" option in your config.
            • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.
       
           You'll find more details and examples of these config options in the docs:
           https://jestjs.io/docs/configuration
           For information about custom transformations, see:
           https://jestjs.io/docs/code-transformation
       
           Details:
       
           /node_modules/@sebgroup/extract/index.js:1
           ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import { startOfMonth, endOfMonth, subDays, addDays, getWeek, isWithinInterval, format, isSameDay, isSameMonth, startOfDay, endOfDay, add, sub, startOfYear, subYears, endOfYear, addYears } from 'date-fns';
                                                                                             ^^^^^^
       
           SyntaxError: Cannot use import statement outside a module

### Steps To Reproduce

run this test on a component that uses the module

````
import { ComponentFixture, TestBed } from '@angular/core/testing';

import { myComponent } from './my-component.component';
import { NggModalModule } from '@sebgroup/green-angular';

describe.skip('MyComponentComponent', () => {
  let component: MyComponentComponent;
  let fixture: ComponentFixture<MyComponentComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [MyComponentComponent, NggModalModule],
    }).compileComponents();

    fixture = TestBed.createComponent(MyComponentComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});


### Current Behaviour

test failed

### Expected Behaviour

test passed

**Comment by mackelito** [comment]
I wonder if this just needs type='module' in package.json?

**Comment by syradar** [comment]
We have been struggling with this to and used this before we switched to Angular Jest builder:

```js
@@ -1,37 +0,0 @@
const { defaultTransformerOptions } = require('jest-preset-angular/presets')

/** @type {import('@jest/types').Config.InitialOptions} */
const config = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setupJest.ts'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  modulePaths: ['<rootDir>', 'src'],
  moduleDirectories: ['node_modules', 'src'],
  transform: {
    '^.+\\.(ts|js|mjs|html|svg)$': [
      'jest-preset-angular',
      {
        ...defaultTransformerOptions,
        tsconfig: '<rootDir>/tsconfig.spec.json',
        stringifyContentPathRegex: '\\.(html|svg)$',
        useESM: true,
      },
    ],
  },
  transformIgnorePatterns: ['node_modules/(?!.*.(js|mjs)$)'],
  restoreMocks: true,
  clearMocks: true,
}

module.exports = config
```

**Comment by splashdust** [comment]
The problem could be that the Green packages contains ES modules that use the regular `.js` extension, when in fact they should use the `.mjs` extension, so tools like Jest can figure out what to do with them.

I'll have a closer look at this, but in the mean time custom jest config will be the way to go.

By default, Jest will *not* transform anything from `node_modules`, so the trick is to exclude the Green stuff in the transformIgnore pattern, so those in fact *will* get transformed:

```js
const esModules = ['@sebgroup/green-angular', '@sebgroup/extract'];
 
...
  transformIgnorePatterns: [
    `/node_modules/(?!.*\\.mjs$|${esModules.join('|')})`
  ],
...
```

**Comment by mackelito** [comment]
Hey.. have you had the time to take a look at this yet?
Let me know If I can assist somehow!

**Comment by mackelito** [comment]
Just got this same problem but when using another green-angular component.
````
    > 12 | import { NggCoreWrapperModule } from '@sebgroup/green-angular';
````
In my template I'm using  <gds-grouped-list *nggCoreElement>...
