### ISSUE TITLE
FilterChip: Close icon not visible in our project.

### ISSUE THREAD

**Issue by VictorAnderfelt** [sebgroup/green#963]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Chlorophyll

### Component name

Filter chip

### Description

The filter chip component's close button is not visible when using it in our project. The project is using angular but this component uses the chlorophyll styling.

![image](https://github.com/sebgroup/green/assets/30840932/a3b3c544-644e-4cb6-bf56-8efa3c95e2a8)

Code:
![MicrosoftTeams-image (38)](https://github.com/sebgroup/green/assets/30840932/92d95065-834d-4230-aa09-c926bd69b609)

Based on:
https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-filter-chip--filter-chip

### Current Behaviour

Close button not showing, but clickable.

### Expected Behaviour

The filter chip should include a visible close button.

**Comment by EldRoos** [comment]
Ja det ser inte ur som rad 73 i green\libs\chlorophyll\scss\components\filter-chip\_mixins.scss triggas. Är någonting med angular, ser ut att fungera fint i vanilla Chlorophyll.

`&-remove {
      &::after {
        content: var(--gds-comp-chips-icon-action-remove);
      }
    }`

**Comment by vsjolander** [comment]
Hey @VictorAnderfelt!

The styling works in Storybook so it might be some styling in your app that interferes with our styling. If you want to I could have a look at it, just ping me in teams.

**Comment by VictorAnderfelt** [comment]
The issue was apparently the Green version in the project. Will close this ticket as completed!
