### ISSUE TITLE
AlertRibbon: wrong text color for success alert

### ISSUE THREAD

**Issue by nikolajus-seb** [sebgroup/green#988]
### Bug already reported?

- [X] I confirm that I have checked if the bug already has been reported

### For which framework/library you are reporting the bug

Chlorophyll

### Component name

AlertRibbon

### Description

Alert ribbon success state currently has black text and icon color, while it should be white as per design library.

### Steps To Reproduce

1. Go to chlorophyll storybook: https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-alert-ribbon--alert-ribbon#element-structure

### Current Behaviour

Black color for success alert ribbon text and icon.

### Expected Behaviour

White color for success alert ribbon text and icon.

**Comment by conandx** [comment]
It's exactly the same colour-issue with the component **Badge**
